import { useState, type MouseEvent } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, Building2, Crosshair, ImagePlus, Loader2, Pencil, Plus, Trash2 } from "lucide-react";
import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { apiUrl } from "@/lib/api-base";
import { apiRequest, getAuthToken } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";

type Service = { id:number; slug:string; title:string; description:string; resultText:string; targetText:string; price:number; sortOrder:number; isActive:boolean; hasImage:boolean; imageFocusX:number; imageFocusY:number };
type Form = { id?:number; slug:string; title:string; description:string; resultText:string; targetText:string; price:number; sortOrder:number; isActive:boolean };
const emptyForm = (order:number):Form => ({ slug:"",title:"",description:"",resultText:"",targetText:"",price:0,sortOrder:order,isActive:true });

export default function AdminOnsiteAssessments(){
  const {toast}=useToast(); const client=useQueryClient();
  const [form,setForm]=useState<Form|null>(null); const [saving,setSaving]=useState(false); const [focus,setFocus]=useState<Service|null>(null);
  const {data:services=[],isLoading}=useQuery<Service[]>({queryKey:["/api/admin/onsite-assessments"]});
  const refresh=()=>client.invalidateQueries({queryKey:["/api/admin/onsite-assessments"]});
  const errorToast=(title:string,error:unknown)=>toast({title,description:error instanceof Error?error.message:"Silakan coba lagi",variant:"destructive"});
  const save=async()=>{if(!form)return;setSaving(true);try{await apiRequest(form.id?"PUT":"POST",form.id?`/api/admin/onsite-assessments/${form.id}`:"/api/admin/onsite-assessments",form);await refresh();setForm(null);toast({title:"Layanan berhasil disimpan"});}catch(error){errorToast("Gagal menyimpan layanan",error);}finally{setSaving(false);}};
  const upload=async(service:Service,file?:File)=>{if(!file)return;if(!["image/jpeg","image/png","image/webp"].includes(file.type)){errorToast("Format gambar tidak didukung",new Error("Gunakan JPG, PNG, atau WebP"));return;}if(file.size>5*1024*1024){errorToast("Gambar terlalu besar",new Error("Ukuran maksimal 5 MB"));return;}try{const response=await fetch(apiUrl(`/api/admin/onsite-assessments/${service.id}/image`),{method:"PUT",headers:{Authorization:`Bearer ${getAuthToken()}`,"Content-Type":file.type,"X-File-Name":encodeURIComponent(file.name)},body:file});if(!response.ok)throw new Error((await response.json().catch(()=>null))?.message||"Upload gagal");await refresh();toast({title:"Gambar berhasil disimpan"});}catch(error){errorToast("Gagal mengunggah gambar",error);}};
  const remove=async(service:Service)=>{if(!confirm(`Hapus ${service.title}? Layanan tidak akan tampil lagi di katalog.`))return;try{await apiRequest("DELETE",`/api/admin/onsite-assessments/${service.id}`);await refresh();toast({title:"Layanan berhasil dihapus"});}catch(error){errorToast("Gagal menghapus layanan",error);}};
  const clickFocus=(event:MouseEvent<HTMLButtonElement>)=>{const box=event.currentTarget.getBoundingClientRect();setFocus(current=>current?{...current,imageFocusX:Math.round(((event.clientX-box.left)/box.width)*100),imageFocusY:Math.round(((event.clientY-box.top)/box.height)*100)}:current);};
  return <div className="min-h-screen bg-gray-50 px-4 py-8"><div className="mx-auto max-w-7xl">
    <Link href="/admin/dashboard" className="mb-6 inline-flex items-center gap-2 text-sm font-semibold text-green-700"><ArrowLeft size={17}/>Kembali ke Dashboard</Link>
    <div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 className="flex items-center gap-3 text-3xl font-extrabold text-gray-900"><Building2 className="text-sky-700"/>Kelola Asesmen Onsite</h1><p className="mt-2 text-gray-600">Tambah, edit, hapus, urutkan, dan kelola gambar katalog layanan Asesmen Onsite.</p></div><Button className="bg-sky-700 hover:bg-sky-800" onClick={()=>setForm(emptyForm(services.length+1))}><Plus className="mr-2 h-4 w-4"/>Tambah Layanan</Button></div>
    <div className="mb-6 rounded-xl border border-sky-200 bg-sky-50 p-4 text-sm leading-6 text-sky-950">Slug dibuat saat layanan ditambahkan dan dipertahankan ketika judul diedit. Penghapusan menggunakan soft delete agar data lebih aman.</div>
    {isLoading?<div className="flex justify-center py-20"><Loader2 className="h-7 w-7 animate-spin text-sky-700"/></div>:<div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{services.map(service=><Card key={service.id} className={`overflow-hidden ${service.isActive?"":"opacity-60"}`}><div className="aspect-[4/3] bg-sky-50">{service.hasImage?<img src={apiUrl(`/api/onsite-assessments/${service.id}/image`)} alt={service.title} className="h-full w-full object-cover" style={{objectPosition:`${service.imageFocusX}% ${service.imageFocusY}%`}}/>:<div className="flex h-full items-center justify-center"><Building2 className="h-12 w-12 text-sky-700"/></div>}</div><CardContent className="p-5"><p className="text-xs font-bold uppercase tracking-wide text-sky-700">Urutan {service.sortOrder} · {service.isActive?"Aktif":"Nonaktif"}</p><h2 className="mt-2 text-lg font-extrabold text-gray-900">{service.title}</h2><p className="mt-2 line-clamp-3 min-h-[3.75rem] text-sm leading-5 text-gray-600">{service.description}</p><p className="mt-3 font-extrabold text-green-700">Rp {service.price.toLocaleString("id-ID")}</p><div className="mt-4 flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={()=>setForm({...service})}><Pencil className="h-4 w-4"/></Button><label className="inline-flex cursor-pointer items-center rounded-md border px-3 py-1.5 text-xs font-semibold"><ImagePlus className="mr-1 h-4 w-4"/>{service.hasImage?"Ganti":"Foto"}<input className="hidden" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{upload(service,e.target.files?.[0]);e.target.value="";}}/></label>{service.hasImage&&<><Button size="sm" variant="outline" onClick={()=>setFocus({...service})}><Crosshair className="h-4 w-4"/></Button><Button size="sm" variant="outline" onClick={async()=>{try{await apiRequest("DELETE",`/api/admin/onsite-assessments/${service.id}/image`);await refresh();}catch(error){errorToast("Gagal menghapus gambar",error);}}}>Hapus Foto</Button></>}<Button size="sm" variant="ghost" onClick={()=>remove(service)}><Trash2 className="h-4 w-4 text-red-600"/></Button></div></CardContent></Card>)}</div>}
  </div>
  <Dialog open={form!==null} onOpenChange={open=>!open&&setForm(null)}>{form&&<DialogContent className="max-h-[92vh] max-w-xl overflow-y-auto"><DialogHeader><DialogTitle>{form.id?"Edit":"Tambah"} Layanan Asesmen Onsite</DialogTitle><DialogDescription>Informasi ini akan tampil pada kartu dan detail katalog publik.</DialogDescription></DialogHeader><div className="space-y-4"><div><Label>Nama layanan</Label><Input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></div>{!form.id&&<div><Label>Slug (opsional)</Label><Input placeholder="dibuat otomatis dari nama" value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})}/></div>}<div><Label>Deskripsi</Label><Textarea rows={5} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div><div><Label>Hasil yang Diperoleh</Label><Textarea rows={4} placeholder="Tuliskan satu poin pada setiap baris" value={form.resultText} onChange={e=>setForm({...form,resultText:e.target.value})}/><p className="mt-1 text-xs text-gray-500">Setiap baris akan ditampilkan sebagai poin pada detail layanan.</p></div><div><Label>Sasaran Tes</Label><Textarea rows={4} placeholder="Tuliskan satu sasaran pada setiap baris" value={form.targetText} onChange={e=>setForm({...form,targetText:e.target.value})}/><p className="mt-1 text-xs text-gray-500">Contoh: Anak usia 6–12 tahun, remaja, atau karyawan.</p></div><div className="grid gap-4 sm:grid-cols-2"><div><Label>Harga</Label><Input type="number" min="0" value={form.price||""} onChange={e=>setForm({...form,price:Number(e.target.value)||0})}/></div><div><Label>Urutan</Label><Input type="number" min="0" value={form.sortOrder} onChange={e=>setForm({...form,sortOrder:Number(e.target.value)||0})}/></div></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.isActive} onChange={e=>setForm({...form,isActive:e.target.checked})}/>Tampilkan di katalog publik</label><div className="flex gap-2"><Button variant="outline" className="flex-1" onClick={()=>setForm(null)}>Batal</Button><Button className="flex-1 bg-sky-700 hover:bg-sky-800" disabled={saving} onClick={save}>{saving&&<Loader2 className="mr-2 h-4 w-4 animate-spin"/>}Simpan</Button></div></div></DialogContent>}</Dialog>
  <Dialog open={focus!==null} onOpenChange={open=>!open&&setFocus(null)}>{focus&&<DialogContent className="max-w-xl"><DialogHeader><DialogTitle>Atur Fokus Gambar</DialogTitle><DialogDescription>Klik bagian gambar yang harus selalu terlihat di kartu.</DialogDescription></DialogHeader><button type="button" onClick={clickFocus} className="relative aspect-[4/3] overflow-hidden rounded-xl bg-gray-100"><img src={apiUrl(`/api/onsite-assessments/${focus.id}/image`)} alt={focus.title} className="h-full w-full object-cover" style={{objectPosition:`${focus.imageFocusX}% ${focus.imageFocusY}%`}}/><span className="absolute h-6 w-6 -translate-x-1/2 -translate-y-1/2 rounded-full border-2 border-white bg-sky-600 shadow" style={{left:`${focus.imageFocusX}%`,top:`${focus.imageFocusY}%`}}/></button><Button className="bg-sky-700" onClick={async()=>{try{await apiRequest("PUT",`/api/admin/onsite-assessments/${focus.id}/image-focus`,{focusX:focus.imageFocusX,focusY:focus.imageFocusY});await refresh();setFocus(null);toast({title:"Fokus gambar disimpan"});}catch(error){errorToast("Gagal menyimpan fokus",error);}}}>Simpan Fokus</Button></DialogContent>}</Dialog>
  </div>;
}
