export const DEFAULT_THERAPY_CATEGORIES = [
  {
    slug: "tumbuh-kembang",
    kind: "development",
    title: "Terapi Tumbuh Kembang",
    description: "Layanan terapi kami dirancang untuk mendukung setiap individu dalam melewati fase perkembangan dengan optimal. Kami menghadirkan intervensi yang disesuaikan dengan kebutuhan unik setiap anak melalui metode yang telah teruji secara ilmiah dan dilakukan oleh tenaga profesional.",
    introduction: "Layanan terapi yang disesuaikan dengan kebutuhan unik setiap anak dan didampingi oleh tenaga profesional.",
    availability: "Layanan anak & remaja",
    summaryItems: ["Terapi wicara", "Terapi perilaku", "Terapi sensori integrasi", "Terapi bermain"],
    theme: "green",
    sortOrder: 1,
  },
  {
    slug: "psikoterapi",
    kind: "psychotherapy",
    title: "Psikoterapi",
    description: "Layanan psikoterapi untuk dewasa di Pelangi Indonesia (RPPI) dirancang untuk membantu individu menghadapi tekanan hidup, hambatan emosional, hingga pengembangan potensi diri.",
    introduction: "Layanan psikoterapi untuk dewasa yang disesuaikan dengan kebutuhan, kondisi, serta tujuan setiap klien.",
    availability: "Pendampingan psikologis",
    summaryItems: ["Konsultasi kebutuhan dan tujuan terapi", "Pendekatan sesuai kondisi klien", "Pendampingan oleh tenaga profesional", "Evaluasi perkembangan secara berkala"],
    theme: "blue",
    sortOrder: 2,
  },
] as const;

export const DEFAULT_THERAPY_SERVICES = [
  {
    categorySlug: "tumbuh-kembang", slug: "terapi-otak-bugar", title: "Terapi Otak Bugar", price: "Rp 150.000/sesi",
    description: "Meningkatkan kemampuan fisik (motorik dan postural), sensoris, dan fokus anak.", fullDescription: "",
    focus: "Meningkatkan kemampuan fisik (motorik dan postural), sensoris, dan fokus anak.",
    target: "Cocok untuk anak dengan ADHD, disleksia, masalah konsentrasi, dan kebutuhan terkait lainnya.",
    benefits: ["Meningkatkan respons terhadap rangsangan sensorik", "Meningkatkan fokus dan perhatian", "Mengurangi kecemasan dan stres", "Meningkatkan keterampilan motorik"], conditions: [], sections: [], sortOrder: 1,
  },
  {
    categorySlug: "tumbuh-kembang", slug: "terapi-perilaku", title: "Terapi Perilaku", price: "Rp 200.000/sesi",
    description: "Meningkatkan kepatuhan serta membentuk perilaku adaptif dan fungsional pada anak.", fullDescription: "",
    focus: "Meningkatkan kepatuhan serta membentuk perilaku adaptif dan fungsional pada anak.",
    target: "Cocok untuk anak dengan Autisme (ASD), ADHD, atau tantrum berlebihan.",
    benefits: ["Meningkatkan keterampilan sosial", "Mengurangi perilaku bermasalah", "Mengembangkan keterampilan komunikasi", "Meningkatkan adaptasi dalam kehidupan sehari-hari"], conditions: [], sections: [], sortOrder: 2,
  },
  {
    categorySlug: "tumbuh-kembang", slug: "terapi-bicara-dan-bahasa", title: "Terapi Bicara dan Bahasa", price: "Rp 150.000/sesi",
    description: "Meningkatkan kemampuan bicara dan bahasa pada anak.", fullDescription: "",
    focus: "Meningkatkan kemampuan bicara dan bahasa pada anak.",
    target: "Cocok untuk anak dengan speech delay, gangguan artikulasi, gangguan pendengaran, atau feeding issues.",
    benefits: ["Mengembangkan bahasa ekspresif dan reseptif", "Mengurangi frustrasi dan tantrum", "Mendukung kesiapan akademis", "Membangun kepercayaan diri", "Meningkatkan kejelasan komunikasi", "Melatih keterampilan motorik oral"], conditions: [], sections: [], sortOrder: 3,
  },
  {
    categorySlug: "psikoterapi", slug: "cognitive-behavior-therapy-cbt", title: "Cognitive Behavior Therapy (CBT)", price: "",
    description: "Pendekatan psikoterapi yang berfokus pada hubungan antara pikiran, perasaan, dan perilaku. CBT umumnya digunakan untuk membantu menangani kecemasan, depresi, trauma dan PTSD, serta Obsessive Compulsive Disorder (OCD).",
    fullDescription: "Cognitive Behavior Therapy (CBT) merupakan pendekatan psikoterapi yang berfokus pada hubungan antara pikiran (kognitif), perasaan, dan perilaku. Pendekatan ini membantu individu mengenali pola pikir yang kurang membantu dan mengembangkan respons yang lebih adaptif.",
    focus: "", target: "", benefits: [], conditions: ["Anxiety (gangguan kecemasan)", "Depresi", "Trauma dan stres (PTSD)", "Obsessive Compulsive Disorder (OCD)"], sections: [], sortOrder: 1,
  },
  {
    categorySlug: "psikoterapi", slug: "dialectical-behavior-therapy-dbt", title: "Dialectical Behavior Therapy (DBT)", price: "",
    description: "Terapi bicara turunan CBT yang dirancang untuk membantu individu dengan emosi sangat intens melalui keseimbangan antara penerimaan diri dan perubahan perilaku positif. Pendekatan ini dapat digunakan pada BPD, bipolar, depresi berat, gangguan makan, PTSD, dan OCD.",
    fullDescription: "Dialectical Behavior Therapy (DBT) adalah terapi bicara turunan dari CBT yang secara khusus dirancang untuk membantu individu yang merasakan emosi dengan sangat intens. Tujuannya adalah menyeimbangkan penerimaan diri dengan perubahan perilaku positif.",
    focus: "", target: "", benefits: [], conditions: ["Borderline Personality Disorder (BPD)", "Bipolar", "Depresi berat", "Eating disorder", "PTSD", "OCD"], sections: [], sortOrder: 2,
  },
  {
    categorySlug: "psikoterapi", slug: "rational-emotive-behavior-therapy-rebt", title: "Rational Emotive Behavior Therapy (REBT)", price: "",
    description: "Pendekatan perilaku kognitif yang membantu mengenali dan mengubah pemikiran irasional yang memengaruhi emosi serta perilaku. REBT dapat digunakan untuk kecemasan, depresi, masalah regulasi emosi, perilaku adiktif, dan trauma.",
    fullDescription: "Rational Emotive Behavior Therapy (REBT) merupakan pendekatan perilaku kognitif yang menekankan keterkaitan antara perasaan, perilaku, dan pikiran. REBT memandang bahwa emosi atau perilaku bermasalah dapat dipengaruhi oleh pemikiran irasional, sehingga fokus penanganannya berada pada pemikiran individu.",
    focus: "", target: "", benefits: [], conditions: ["Anxiety (gangguan kecemasan)", "Depresi", "Masalah kemampuan emosi", "Kecanduan dan perilaku adiktif", "Trauma"], sections: [], sortOrder: 3,
  },
  {
    categorySlug: "psikoterapi", slug: "mind-over-mood-mom", title: "Mind Over Mood (MOM)", price: "",
    description: "Program yang membantu memperbaiki suasana hati dengan mengidentifikasi, mengevaluasi, dan mengubah pikiran negatif. Metode ini dapat mendukung penanganan bipolar, PTSD, masalah kemarahan, dan stres.",
    fullDescription: "Mind Over Mood (MOM) adalah program yang membantu mengubah suasana hati dengan cara mengidentifikasi, mengevaluasi, dan mengubah pikiran negatif. Prosesnya membantu individu memahami pengaruh pikiran terhadap emosi dan respons sehari-hari.",
    focus: "", target: "", benefits: [], conditions: ["Bipolar", "PTSD", "Anger issues", "Stres"], sections: [], sortOrder: 4,
  },
  {
    categorySlug: "psikoterapi", slug: "eye-movement-desensitization-and-reprocessing-emdr", title: "Eye Movement Desensitization and Reprocessing (EMDR)", price: "",
    description: "Psikoterapi interaktif yang menggunakan stimulasi bilateral, termasuk gerakan mata, untuk membantu pemrosesan memori traumatis secara lebih adaptif. EMDR digunakan terutama untuk PTSD serta dapat diterapkan pada fobia, kecemasan, dan depresi.",
    fullDescription: "Eye Movement Desensitization and Reprocessing (EMDR) adalah psikoterapi interaktif yang dirancang untuk membantu seseorang memulihkan diri dari trauma dan mengurangi stres psikologis. Terapi ini merangsang kedua sisi otak melalui gerakan mata atau stimulasi fisik lain agar memori traumatis dapat diproses dengan lebih adaptif.",
    focus: "", target: "", benefits: [], conditions: ["Gangguan stres pascatrauma (PTSD)", "Fobia", "Anxiety (gangguan kecemasan)", "Depresi"], sections: [], sortOrder: 5,
  },
  {
    categorySlug: "psikoterapi", slug: "brainspotting", title: "Brainspotting", price: "",
    description: "Teknik psikoterapi berbasis pikiran dan tubuh yang memanfaatkan arah pandangan mata untuk membantu memproses trauma, emosi negatif, stres, dan pengalaman yang sulit dijangkau melalui kata-kata. Pendekatan ini dapat digunakan pada PTSD, depresi, kecemasan, fobia, dan OCD.",
    fullDescription: "Brainspotting merupakan teknik psikoterapi berbasis pikiran dan tubuh yang digunakan untuk memproses dan melepaskan trauma, emosi negatif, stres, hingga nyeri fisik yang tersimpan. Metode ini memanfaatkan arah pandangan mata (fiksasi) untuk mengakses memori bawah sadar yang sulit dijangkau hanya dengan kata-kata.",
    focus: "", target: "", benefits: [], conditions: ["PTSD dan trauma", "Depresi dan kecemasan", "Fobia", "OCD"], sections: [], sortOrder: 6,
  },
  {
    categorySlug: "psikoterapi", slug: "clinical-hypnotherapy", title: "Clinical Hypnotherapy", price: "",
    description: "Metode terapi psikologis yang menggunakan kondisi relaksasi mendalam untuk membantu individu lebih terbuka terhadap sugesti positif. Pendekatan ini dapat digunakan untuk kecemasan, trauma dan PTSD, fobia, depresi, kebiasaan adiktif, insomnia, serta keluhan psikosomatis.",
    fullDescription: "Clinical Hypnotherapy adalah metode terapi psikologis yang menggunakan teknik hipnosis untuk membawa seseorang ke kondisi relaksasi yang sangat dalam (trance). Dalam kondisi ini, pikiran bawah sadar menjadi lebih terbuka terhadap sugesti positif untuk membantu mengatasi masalah emosi, perilaku, trauma, fobia, hingga keluhan psikosomatis.",
    focus: "", target: "", benefits: [], conditions: ["Anxiety", "Trauma dan PTSD", "Fobia", "Depresi", "Gangguan kebiasaan dan kecanduan", "Gangguan tidur (insomnia)", "Keluhan psikosomatis"], sections: [], sortOrder: 7,
  },
  {
    categorySlug: "psikoterapi", slug: "mindfulness-based-stress-reduction-mbsr", title: "Mindfulness Based Stress Reduction (MBSR)", price: "",
    description: "Program pelatihan mindfulness terstruktur selama delapan minggu untuk membantu individu hadir pada masa kini dengan penuh kesadaran tanpa menghakimi. MBSR dapat mendukung pengelolaan stres, kecemasan, depresi, nyeri kronis, burnout, gangguan tidur, dan depresi postpartum.",
    fullDescription: "Mindfulness Based Stress Reduction (MBSR) adalah program pelatihan terstruktur selama delapan minggu yang dirancang untuk membantu individu mengelola stres, kecemasan, depresi, dan nyeri kronis. Metode ini melatih individu untuk hadir sepenuhnya pada masa kini dengan penuh kesadaran dan tanpa menghakimi.",
    focus: "", target: "", benefits: [], conditions: ["Anxiety", "Depresi", "Stres kronis dan burnout", "Gangguan tidur", "Postpartum depression"], sections: [], sortOrder: 8,
  },
  {
    categorySlug: "psikoterapi", slug: "mindfulness-based-cognitive-therapy-mbct", title: "Mindfulness Based Cognitive Therapy (MBCT)", price: "",
    description: "Psikoterapi yang menggabungkan CBT dengan meditasi mindfulness untuk membantu individu mengenali pikiran negatif tanpa menghakiminya. MBCT digunakan untuk membantu mencegah kekambuhan depresi serta menangani kecemasan dan stres kronis.",
    fullDescription: "Mindfulness Based Cognitive Therapy (MBCT) menggabungkan teknik CBT dengan meditasi kesadaran penuh (mindfulness). Terapi ini melatih individu untuk hidup pada masa kini (here and now) dan mengenali pikiran negatif tanpa menghakiminya, guna membantu mencegah kekambuhan depresi.",
    focus: "", target: "", benefits: [], conditions: ["Depresi mayor", "Gangguan kecemasan", "Stres kronis"], sections: [], sortOrder: 9,
  },
  {
    categorySlug: "psikoterapi", slug: "art-therapy", title: "Art Therapy", price: "",
    description: "Bentuk psikoterapi yang menggunakan media seni sebagai sarana mengekspresikan dan memahami emosi yang sulit disampaikan melalui kata-kata. Art Therapy dapat digunakan dalam penanganan trauma, PTSD, depresi, kecemasan, stres kronis, dan adiksi.",
    fullDescription: "Art Therapy adalah bentuk psikoterapi yang menggunakan media seni, seperti menggambar, melukis, mewarnai, atau memahat, sebagai sarana utama untuk mengekspresikan emosi. Pendekatan ini membantu individu mengeluarkan perasaan yang sulit diungkapkan melalui kata-kata dan memahami emosi bawah sadar.",
    focus: "", target: "", benefits: [], conditions: ["Trauma dan PTSD", "Depresi", "Anxiety", "Stres kronis", "Kecanduan (adiksi)"], sections: [], sortOrder: 10,
  },
  {
    categorySlug: "psikoterapi", slug: "emotional-freedom-technique-eft", title: "Emotional Freedom Technique (EFT)", price: "",
    description: "Metode yang dikenal sebagai tapping dan menggabungkan pendekatan psikologis dengan stimulasi titik tertentu pada tubuh sambil melafalkan afirmasi. EFT digunakan sebagai pendekatan pendamping untuk trauma, PTSD, kecemasan, depresi, dan stres.",
    fullDescription: "Emotional Freedom Technique (EFT), dikenal juga sebagai tapping, adalah metode terapi alternatif yang menggabungkan pendekatan psikologis dengan stimulasi titik energi tubuh seperti akupunktur tanpa jarum. Teknik dilakukan dengan mengetuk titik-titik tertentu menggunakan jari sambil melafalkan afirmasi atau doa.",
    focus: "", target: "", benefits: [], conditions: ["Trauma dan PTSD", "Anxiety", "Depresi", "Stres"], sections: [], sortOrder: 11,
  },
  {
    categorySlug: "psikoterapi", slug: "touch-for-health-tfh", title: "Touch For Health (TFH)", price: "",
    description: "Pendekatan komplementer yang memadukan prinsip akupresur, meridian, dan kinesiologi melalui muscle testing sebagai biofeedback. TFH digunakan untuk mendukung manajemen stres serta membantu keluhan kecemasan, depresi ringan, dan burnout.",
    fullDescription: "Touch For Health (TFH) merupakan metode terapi komplementer dan perawatan diri holistik yang menggabungkan prinsip pengobatan Timur, seperti akupresur dan meridian, dengan ilmu kinesiologi Barat. Metode ini menggunakan muscle testing sebagai biofeedback untuk mendukung keseimbangan tubuh, mengurangi stres, dan meningkatkan vitalitas.",
    focus: "", target: "", benefits: [], conditions: ["Anxiety", "Depresi ringan", "Burnout"], sections: [], sortOrder: 12,
  },
  {
    categorySlug: "psikoterapi", slug: "meridian-pace-pmr", title: "Meridian/PACE/PMR", price: "",
    description: "Gabungan pendekatan integratif: Meridian menggunakan stimulasi titik tubuh untuk mendukung regulasi emosi; PACE membangun rasa aman melalui playfulness, acceptance, curiosity, dan empathy; sedangkan PMR menggunakan relaksasi otot progresif untuk mengurangi kecemasan, stres, depresi, dan gangguan tidur.",
    fullDescription: "Tiga pendekatan yang digunakan sesuai kebutuhan untuk mendukung regulasi emosi, membangun rasa aman, dan membantu relaksasi fisik.", focus: "", target: "", benefits: [], conditions: [],
    sections: [
      { title: "Meridian", description: "Meridian lebih sering digunakan dalam pendekatan psikologi alternatif atau integratif yang dipengaruhi pengobatan tradisional Tiongkok. Secara teori, stimulasi pada titik tertentu dipercaya dapat membantu regulasi emosi dengan mendukung keseimbangan aliran energi pada meridian.", conditions: ["Stres dan anxiety", "PTSD dan fobia", "Depresi ringan"] },
      { title: "PACE", description: "PACE adalah singkatan dari Playfulness (Keceriaan), Acceptance (Penerimaan), Curiosity (Rasa Ingin Tahu), dan Empathy (Empati). PACE digunakan sebagai pendekatan komunikasi dan pola asuh untuk membangun rasa aman, mengurangi sikap defensif, serta membantu anak memproses emosi.", conditions: ["Trauma masa kecil (developmental trauma)", "Attachment disorder"] },
      { title: "PMR", description: "Progressive Muscle Relaxation (PMR) adalah teknik relaksasi fisik untuk mengurangi kecemasan, stres, dan ketegangan otot dengan cara mengencangkan lalu melepaskan kelompok otot tertentu secara berurutan.", conditions: ["Anxiety", "Stres", "Depresi", "Gangguan tidur (insomnia)"] },
    ], sortOrder: 13,
  },
  {
    categorySlug: "psikoterapi", slug: "tension-trauma-releasing-exercises-tre", title: "Tension & Trauma Releasing Exercises (TRE)", price: "",
    description: "Serangkaian latihan fisik yang dirancang untuk membantu tubuh melepaskan stres, ketegangan, dan trauma yang tersimpan dalam otot. Teknik ini digunakan untuk membantu meredakan gejala stres, kecemasan, dan dampak trauma secara fisik.",
    fullDescription: "Tension & Trauma Releasing Exercises (TRE) merupakan serangkaian latihan fisik yang dirancang untuk membantu tubuh melepaskan stres, ketegangan, dan trauma yang tersimpan di dalam otot.",
    focus: "", target: "", benefits: [], conditions: ["Gejala stres", "Kecemasan", "Trauma secara fisik"], sections: [], sortOrder: 14,
  },
  {
    categorySlug: "psikoterapi", slug: "brain-gym", title: "Brain Gym", price: "",
    description: "Serangkaian gerakan fisik sederhana untuk mendukung koordinasi tubuh serta kemampuan kognitif seperti fokus dan daya ingat. Latihan ini dapat digunakan untuk membantu mengelola stres, kecemasan, dan mendukung rehabilitasi gangguan jiwa berat.",
    fullDescription: "Brain Gym berupa serangkaian gerakan fisik sederhana yang dirancang untuk mengoptimalkan fungsi otak. Terapi non-invasif ini bertujuan menyeimbangkan kerja otak kiri dan kanan, memperbaiki koordinasi tubuh, serta merangsang kemampuan kognitif seperti fokus dan daya ingat.",
    focus: "", target: "", benefits: [], conditions: ["Membantu mengelola gejala stres", "Anxiety", "Mendukung rehabilitasi gangguan jiwa berat"], sections: [], sortOrder: 15,
  },
  {
    categorySlug: "psikoterapi", slug: "psikologi-positif", title: "Psikologi Positif", price: "",
    description: "Pendekatan yang berfokus pada pengembangan kekuatan karakter, emosi positif, kebahagiaan, dan makna hidup. Dalam psikoterapi, pendekatan ini dapat membantu individu menghadapi kecemasan, trauma dan PTSD, serta stres kronis.",
    fullDescription: "Psikologi Positif merupakan cabang ilmu psikologi yang berfokus pada pengembangan kekuatan karakter, emosi positif, dan makna hidup. Saat digunakan sebagai pendekatan terapi, metodenya berfokus membangun kebahagiaan untuk membantu mengatasi gejala depresi dan kecemasan.",
    focus: "", target: "", benefits: [], conditions: ["Gangguan kecemasan (anxiety)", "Trauma (PTSD)", "Stres kronis"], sections: [], sortOrder: 16,
  },
] as const;
